select PROFILE_ID,
       ACCOUNT_ID,
       PROFILE_CREATION_TIME,
       PROFILE_AGE,
       PROFILE_GENDER,
       CORE_SP_PROFILES.FIRST_LOCAL_LANGUAGE as LANGUAGE,
       CORE_SP_PROFILES.FIRST_LOCAL_COUNTRY as COUNTRY,
       CORE_SP_PROFILES.LATEST_COURSE_FINISHED as LATEST_COURSE_FINISHED,
       CORE_SP_PROFILES.IS_MIDI_USAGE as IS_MIDI_USAGE,
       CORE_SP_PROFILES.IS_HEADPHONES_USAGE as IS_HEADPHONES_USAGE,
       IS_DELETED,
       CORE_SP_PROFILES.LAST_DEVICE_MODEL_VERSION as LAST_DEVICE_MODEL_VERSION,
       CORE_SP_PROFILES.ACCOUNT_HAS_CURRENT_ACTIVE_SUBSCRIPTION as HAS_CURRENT_ACTIVE_SUBSCRIPTION,
       CORE_SP_PROFILES.ACCOUNT_FIRST_NON_ZERO_TRANSACTION_TS as SUBSCRIPTION_TIME,
       CORE_SP_PROFILES.FIRST_EXPERIENCE_ANSWER as FIRST_EXPERIENCE_ANSWER,
       IS_EVER_PREMIUM_ACCESS as WAS_EVER_SUBSCRIBED,
       max(CORE_SP_DEVICES_AND_ACCOUNTS.RELATED_ADULT_RP_PROFILES) as NUMBER_OF_ADULTS_IN_HOUSEHOLD,
       max(CORE_SP_DEVICES_AND_ACCOUNTS.RELATED_CHILD_RP_PROFILES) as NUMBER_OF_CHILDREN_IN_HOUSEHOLD
from CORE_SP_PROFILES
join CORE_SP_DEVICES_AND_ACCOUNTS on CORE_SP_DEVICES_AND_ACCOUNTS.GLOBAL_ACCOUNT_ID = CORE_SP_PROFILES.ACCOUNT_ID
where PROFILE_ID='$profile_id'
-- where PROFILE_ID = 'PFL644ECE8C38C124.48555461'
group by PROFILE_ID, ACCOUNT_ID, PROFILE_CREATION_TIME, PROFILE_AGE,
         PROFILE_GENDER, CORE_SP_PROFILES.FIRST_LOCAL_LANGUAGE, CORE_SP_PROFILES.FIRST_LOCAL_COUNTRY,
         CORE_SP_PROFILES.LATEST_COURSE_FINISHED, CORE_SP_PROFILES.IS_MIDI_USAGE, CORE_SP_PROFILES.IS_HEADPHONES_USAGE,
         IS_DELETED, CORE_SP_PROFILES.LAST_DEVICE_MODEL_VERSION,
         CORE_SP_PROFILES.ACCOUNT_HAS_CURRENT_ACTIVE_SUBSCRIPTION,
         CORE_SP_PROFILES.ACCOUNT_FIRST_NON_ZERO_TRANSACTION_TS,
         CORE_SP_PROFILES.FIRST_EXPERIENCE_ANSWER,
         IS_EVER_PREMIUM_ACCESS


-- select * from CORE_SP_PROFILE_SESSIONS where PROFILE_ID='PFL644ECE8C38C124.48555461'